[build]
    command = "gunicorn --bind 0.0.0.0:8000 --workers 1 -k sync functions.app:app"
    publish = "static"
    functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11.9" # or the version you are using.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200