[build]
 command = "gunicorn functions.app:app"  # app:app is your flask file and flask instance
 publish = "static" # This is important, as we are serving static files.
 functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11.9" # or the version you are using.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200