[build]
  command = "pip install -r requirements.txt"
  publish = "dist"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
  publish = "dist" 