# Netlify configuration for Portfolio Website
# This file defines the build settings and redirects for Netlify deployment

[build]
  # Command to build the static site - use explicit Python version and handle errors gracefully
  command = "python build_static_site.py"
  
  # Directory that contains the deployed site
  publish = "app/static/"

[build.environment]
  # Specify Python version for the build
  PYTHON_VERSION = "3.9"

# Handle 404 errors by redirecting to the index page
[[redirects]]
  from = "/*"
  to = "/html/:splat.html"
  status = 200
  force = false

# Redirect /static/* paths to the correct location
[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 301

# Optional: Enable Netlify Dev for local development
[dev]
  command = "python run.py"
  port = 5000

[functions]
  directory = "netlify/functions"

[context.production.environment]
  STATIC_DEPLOYMENT = "true"
  IMAGE_FAVICON_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/FavIcon"
  IMAGE_LOGO_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Logo"
  IMAGE_BANNER_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Banner"

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200
  force = true 