# Netlify configuration for Portfolio Website
# This file defines the build settings and redirects for Netlify deployment

[build]
  # Directory to publish (relative to root of the repo)
  publish = "app/static"
  # Default build command
  command = "python build_static_site.py"

# Headers to set on static site
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.amazonaws.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com 'unsafe-inline'; img-src 'self' https://*.amazonaws.com data:; connect-src 'self' https://*.amazonaws.com;"

# Redirect all requests to the root if no path exists
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Environment variables for the build
[build.environment]
  STATIC_DEPLOYMENT = "true"
  PYTHONUNBUFFERED = "1"
  
# Use Python 3.11
[build.environment]
  PYTHON_VERSION = "3.11"

# Plugin for Python dependencies
[[plugins]]
  package = "@netlify/plugin-python"

# Optional: Enable Netlify Dev for local development
[dev]
  command = "python run.py"
  port = 5000

[functions]
  directory = "netlify/functions"

[context.production.environment]
  STATIC_DEPLOYMENT = "true"
  IMAGE_FAVICON_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/FavIcon"
  IMAGE_LOGO_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Logo"
  IMAGE_BANNER_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Banner"

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200
  force = true 