# Netlify configuration for Portfolio Website
# This file defines the build settings and redirects for Netlify deployment

[build]
  # Directory to publish (relative to root of the repo)
  publish = "app/static"
  # Default build command
  command = "python build_static_site.py"
  environment = { PYTHON_VERSION = "3.11", STATIC_DEPLOYMENT = "true", PYTHONUNBUFFERED = "1" }

# Headers to set on static site
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.amazonaws.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com 'unsafe-inline'; img-src 'self' https://*.amazonaws.com data:; connect-src 'self' https://*.amazonaws.com;"

# Redirect all requests to the root if no path exists
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[dev]
  command = "python app.py"
  port = 8888
  targetPort = 5000

[functions]
  directory = "netlify/functions"

# Redirects for the admin interface
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# API proxy for the functions
[[redirects]]
  from = "/api/about-content"
  to = "/.netlify/functions/get-content"
  status = 200

# Environment variables for production (REPLACE WITH YOUR VALUES)
[context.production.environment]
  STATIC_DEPLOYMENT = "true"
  IMAGE_FAVICON_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/FavIcon"
  IMAGE_LOGO_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Logo"
  IMAGE_BANNER_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Banner"
  IMAGE_ABOUT_PROFILE_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Adobe+Express+-+file.png"
  IMAGE_ABOUT_PHOTO1_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/IMG_0138.jpg"
  IMAGE_ABOUT_PHOTO2_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/IMG_0915.jpg"
  IMAGE_ABOUT_PHOTO3_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/IMG_1461.jpg"
  IMAGE_ABOUT_PHOTO4_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/IMG_1627.jpg"
  
  # Security token for content updating - create a strong random token
  UPDATE_CONTENT_TOKEN = "CREATE_A_STRONG_RANDOM_TOKEN_HERE"

# Environment variables for development
[context.development.environment]
  STATIC_DEPLOYMENT = "false"
  IMAGE_FAVICON_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/FavIcon"
  IMAGE_LOGO_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Logo"
  IMAGE_BANNER_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Banner"
  IMAGE_ABOUT_PROFILE_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/profilephoto+(2).svg"
  IMAGE_ABOUT_PHOTO1_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/about_photo1.jpg"
  IMAGE_ABOUT_PHOTO2_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/about_photo2.jpg"
  IMAGE_ABOUT_PHOTO3_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/about_photo3.jpg"
  IMAGE_ABOUT_PHOTO4_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/about_photo4.jpg" 