[build]
  command = "pip install -r requirements.txt && python build_static_site.py"
  publish = "app/static"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "python app.py"
  port = 5000
  publish = "dist" 