# Netlify configuration for Portfolio Website
# This file defines the build settings and redirects for Netlify deployment

[build]
  # Command to build the static site
  command = "pip install -r requirements.txt && python build_static_site.py"
  
  # Directory that contains the deployed site
  publish = "app/static"

[build.environment]
  # Specify Python version for the build
  PYTHON_VERSION = "3.9"

# Handle 404 errors by redirecting to the index page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect /static/* paths to the correct location
[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 301

# Optional: Enable Netlify Dev for local development
[dev]
  command = "python run.py"
  port = 5000

[functions]
  directory = "netlify/functions" 