[build]
    command = "echo 'Build Successful'"  # A placeholder build command
    publish = "."  # Publish the root directory
    # Remove the functions setting

[[redirects]]
    from = "/*"
    to = "templates/index.html"
    status = 200