# Netlify configuration for Portfolio Website
# This file defines the build settings and redirects for Netlify deployment

[build]
  # Command to build the static site
  command = "python build_static_site.py"
  
  # Directory that contains the deployed site
  publish = "app/static/"

[build.environment]
  # Specify Python version for the build
  PYTHON_VERSION = "3.9"

# Context-specific environment variables
[context.production.environment]
  STATIC_DEPLOYMENT = "true"
  IMAGE_FAVICON_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/FavIcon"
  IMAGE_LOGO_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Logo" 
  IMAGE_BANNER_URL = "https://website-majorjayant.s3.eu-north-1.amazonaws.com/Banner"

# Handle root path
[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200
  force = true

# Route all path requests to the corresponding HTML files
[[redirects]]
  from = "/*"
  to = "/html/:splat.html"
  status = 200
  force = false

# Make sure static CSS files are properly served
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/css"

# Handle image files
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Make sure CSS is properly served even without extension
[[redirects]]
  from = "/css/style"
  to = "/css/style.css"
  status = 200
  force = true

# Redirect specific asset paths to their correct locations
[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 301

# Optional: Enable Netlify Dev for local development
[dev]
  command = "python app.py"
  port = 5000

[functions]
  directory = "netlify/functions" 